### ISSUE TITLE
[MAUI] iOS nuget package is missing types

### ISSUE THREAD

**Issue by AdamDiament** [VisualService/dotnet-zoom-meeting-SDK#10]
@mdima I added a sample project on [this branch](https://github.com/VisualService/Xamarin.ZoomSDKBinding/tree/feature/sample-projects) to try to get your iOS integration working. It references the MobileRTC project directly rather than the nuget package *. [Here ](https://github.com/VisualService/Xamarin.ZoomSDKBinding/blob/feature/sample-projects/VisualService.Xamarin.ZoomSDKBinding.sln)is the sln file to open in Visual Studio

The sample project works fine when referencing the mobile rtc project directly. But when referencing the Nuget package (https://www.nuget.org/packages/VisualService.Xamarin.iOS.ZoomSDK) the resulting namespace (Zoomios) seems to be missing a bunch of needed classes and interfaces compared to referencing the mobile RTC project directly. Is it possible the packaging config needs looking at? Or that I published the wrong package? I took the one in /Xamarin.ZoomSDKBinding/src/iOS/MobileRTC_iOS/bin/Release

Any chance you could take a look please?

**Comment by AdamDiament** [comment]
@mdima Actually I got it working, I just needed to add some permissions to the info.plist. If you could still take a look at the nuget package issue that would be wonderful.

**Comment by mdima** [comment]
@AdamDiament I take a look at it.

**Comment by mdima** [comment]
At first sight it seems an issue with the latest release of Visual Studio 2022. 
I have this doubt because I can reproduce the same issue with the source code of the package Xamarin.ZoomBinding that some weeks ago were running without any problem. 
I am investigating if it is a breaking change in something or just a bug.

**Comment by mdima** [comment]
It seems also other developers are having the same problem, on MAUI... I added a comment here: https://github.com/xamarin/xamarin-macios/issues/16192

**Comment by mdima** [comment]
I created a different issue after the comment of an administrator. The new issue is here: 
https://github.com/xamarin/xamarin-macios/issues/16299

**Comment by XamarinRPMTeam** [comment]
@AdamDiament 
When we refer **VisualService.Xamarin.iOS.ZoomSDK(version 5.11.10.4556)** we are getting below issue as per the screenshot . We are not able consume the class inside this .Could you please assist on this . Thanks in advance 

<img width="922" alt="Screen Shot 2022-10-26 at 9 22 33 AM" src="https://user-images.githubusercontent.com/50828024/197941997-214fc619-2d61-460c-ae66-80ec76394109.png">

**Comment by umeshkamble** [comment]
> 

@AdamDiament @mdima @icalderond 
I am also facing same issue.  I have added **VisualService.Xamarin.iOS.ZoomSDK** package

**Comment by mdima** [comment]
Yes, I have read somewhere that it is a known issue of IntelliCode. Anyway the program compiles.

**Comment by umeshkamble** [comment]
I am not able to compile the application. it is showing assembly reference missing. 
 
<img width="925" alt="Screen Shot 2022-10-27 at 1 29 40 PM" src="https://user-images.githubusercontent.com/5494166/198248510-f13449aa-67aa-473c-8da9-75108fa71fdb.png">

**Comment by mdima** [comment]
Hi @umeshkamble , 
   ok, do like this. 

Compile the MobileRTC_iOS with the Release profile. Visual Studio will create a Nuget package (bin\Release\VisualService.Xamarin.iOS.ZoomSDK.5.11.10.4556.nupkg). 

In the ZoomSDKSampleApp.iOS project remove the reference to the MobileRTC_iOS project, then the local Nuget package created. 
This workaround will make the iOS test application compile. 

In the while we are still waiting for an answer to this: https://github.com/xamarin/xamarin-macios/issues/16299#issuecomment-1283642902 and this https://github.com/xamarin/xamarin-macios/issues/16192#issuecomment-1294671343 issues in Xamarin. 
I hope we will receive an answer since Xamarin Forms should still be supported by Microsoft (until 5/2024). 

Have a good day,
Michele

**Comment by XamarinRPMTeam** [comment]
@mdima 
Thanks for your response .I have tried the same steps as you provided .Compiled the MobileRTC_iOS project in release mode and in the sample project referred to the local nuget package created in bin\Release\VisualService.Xamarin.iOS.ZoomSDK.5.11.10.4556.nupkg. Its not compiled 

**Screenshot1:-**
<img width="500" alt="Screen Shot 2022-10-30 at 10 45 34 AM" src="https://user-images.githubusercontent.com/50828024/198866309-5bfec894-857b-4b8f-87cc-0b18df8f6b9f.png">

**Screenshot2:-**
<img width="500" alt="Screen Shot 2022-10-30 at 10 48 07 AM" src="https://user-images.githubusercontent.com/50828024/198866333-ecd0112b-84b2-4362-bdce-6104629125cb.png">

**Trial 2:-**
Gave reference to the project MobileRTC_iOS , its compiling and running the app . But while joining status shows as connecting and crashing immeditly .In the hosting device it shows admit button as well. The problem is the sample app crashing immediatly while joining 

**Screenshot1:-**
![IMG_2072](https://user-images.githubusercontent.com/50828024/198866449-8e0e8bca-aa52-4da5-a783-8f57817ad5ea.PNG)

**Screenshot2:-**
<img width="645" alt="Screen Shot 2022-10-30 at 10 57 51 AM" src="https://user-images.githubusercontent.com/50828024/198866459-91b2ea36-368c-4908-8a6b-d46c98d59e4c.png">

Could you please check comment on this . Thanks

**Comment by AmrYousef** [comment]
Hi All, Any Updates? did anyone find any solution/workaround?

thanks

**Comment by AmrYousef** [comment]
Or even if there is any workaround, I'm stuck

**Comment by mdima** [comment]
Hi, well... using the workaround above (referencing the Nuget package) works, at least using Visual Studio on Windows. 

https://user-images.githubusercontent.com/1006461/199481409-f4b02011-74be-4702-8a67-ba35f281f848.mp4

**Comment by XamarinRPMTeam** [comment]
@mdima 

Thanks for the response . Even from windows we tried on 2 days back  .We used Visual studio 2022 preview in windows machine with the given work around . And we got the same error .  The classes / interfaces from the package could not found error message comes . Could you please let us know what could be the issue . Or if you have the iOS working sample could you please upload it here . 

<img width="400" alt="Screen Shot 2022-11-09 at 9 41 27 AM" src="https://user-images.githubusercontent.com/50828024/200748595-4c4b4483-ae06-4e0d-be56-e7922d2bea10.png">

**Comment by AmrYousef** [comment]
Hi @mdima, I went through the steps mentioned and I ended up having the same issue. Importing zoom into my project is very important and any help would be appreciated

Thanks

**Comment by AdamDiament** [comment]
@mdima I'm not sure of your work situation - but my company is looking to bring on some extra resource to help integrate the iOS version into our solution - would you be available for some paid freelance work?

**Comment by mdima** [comment]
@AdamDiament, well... call me on Skype, my account is michele73 .

**Comment by AdamDiament** [comment]
@timjamwoo could you please have a look at this one for Xamarin Forms, since you have recently got the MAUI one working?

- [ ] Create a nuget package from the latest Xamarin Forms iOS version
- [ ] Test the package in the Visual Service tech app
- [ ] Fix any remaining issues 
- [ ] Pass package to me for upload to nuget.org

**Comment by AdamDiament** [comment]
Closing this issue as Xamarin is now out of support. iOS MAUI McNuget is working fine
