### ISSUE TITLE
Zoom meeting not working

### ISSUE THREAD

**Issue by hksharafudheen** [VisualService/dotnet-zoom-meeting-SDK#44]
Hello, I am having issue with connecting zoom in my Xamarin application. Zoom meeting is one of the major feature in the app which is blocked now. We are using the nuget version v5.15.10.15778 and the iOS mobile RTC version 5.15.7.9685. We are in the process of migration of our app, however it will take sometime as it is huge. Can you please let me know, if it is due to the minimum sdk version policy of Zoom that it is not working now? If yes, is there any possible way to integrate the nuget for some more months until we migrate?

**Comment by hksharafudheen** [comment]
@AdamDiament , @timjamwoo Please help...

**Comment by AdamDiament** [comment]
Hi @hksharafudheen - thanks for getting in touch and I'm glad to see this library being used in the wild. 

As per the readme file, as of May 2024 Xamarin Forms is no longer supported by Microsoft. So unfortunately, we will not be providing new updates to this library for the XF version. You're welcome to fork the repo and do the upgrade yourself if you want to [provide ongoing legacy Xamarin Forms support (there are instructions in the readme). However I would strongly suggest putting your resources into completing the upgrade of your XF app to MAUI instead. Sooner or later your XF form app will not be accepted for update in the app stores anyway due to OS version incompatibility issues, if it hasn't happened already.

Regards!

Adam and the VS team

**Comment by AdamDiament** [comment]
@hksharafudheen Out of interest, could you point me to your app so I can see how you are using the library please?

**Comment by AdamDiament** [comment]
I'm closing this issue as there was no reply, and we don't plan to provide legacy- support for xamarin forms
